FROM golang:1.25-alpine AS builder

WORKDIR /app

# Install build dependencies for CGO (required for go-sqlite3)
RUN apk add --no-cache typst gcc musl-dev

# Enable CGO
ENV CGO_ENABLED=1


RUN addgroup -S appuser && adduser -S appuser -G appuser

COPY ./backend/go.mod ./backend/go.sum ./
COPY ./backend .

RUN go mod download
RUN go install github.com/air-verse/air@v1.62.0
RUN go build -o api ./cmd/api

RUN chown appuser:appuser /app/api

RUN mkdir -p /usr/share/fonts/custom_fonts
COPY ./assets/Poppins /usr/share/fonts/custom_fonts
RUN apk add --no-cache fontconfig
RUN fc-cache -f -v

EXPOSE 1234

CMD ["air", "-c", ".air.toml"]

