import type { ComponentInstance, GridConfig } from '../types/template';
import { hasAbsolutePosition } from '../types/template';
import { componentGenerators } from './componentGenerators';

export function generateTypst(state: { components: ComponentInstance[]; grid: GridConfig }): string {
    if (state.components.length === 0) {
        return '// No components added yet\n// Drag components from the palette to start building your template';
    }

    // Generate header
    const header = generateHeader();

    // Filter to only top-level components (those with absolute positions)
    const topLevelComponents = state.components.filter(c => hasAbsolutePosition(c.position));

    // Group components by row
    const componentsByRow: Record<number, typeof topLevelComponents> = {};
    topLevelComponents.forEach((component) => {
        if (hasAbsolutePosition(component.position)) {
            const row = component.position.row;
            if (!componentsByRow[row]) {
                componentsByRow[row] = [];
            }
            componentsByRow[row].push(component);
        }
    });

    // Sort rows
    const rows = Object.keys(componentsByRow)
        .map(Number)
        .sort((a, b) => a - b);

    // Generate body
    const body: string[] = [];

    rows.forEach((rowIndex) => {
        const rowComponents = componentsByRow[rowIndex] || [];

        // Sort components by column
        const sortedComponents = [...rowComponents].sort((a, b) => {
            const aCol = hasAbsolutePosition(a.position) ? a.position.column : 0;
            const bCol = hasAbsolutePosition(b.position) ? b.position.column : 0;
            return aCol - bCol;
        });

        // If only one component in the row, render it directly
        if (sortedComponents.length === 1) {
            const component = sortedComponents[0];
            const generator = componentGenerators[component.type];
            if (generator) {
                body.push(generator(component));
            }
        } else {
            // Multiple components in row - use grid layout
            const colWidths: string[] = [];
            const components: string[] = [];

            sortedComponents.forEach((component) => {
                if (hasAbsolutePosition(component.position)) {
                    const spanFraction = component.position.span / state.grid.columns;
                    colWidths.push(`${spanFraction}fr`);

                    const generator = componentGenerators[component.type];
                    if (generator) {
                        components.push(generator(component));
                    }
                }
            });

            const gridCode = `#grid(
  columns: (${colWidths.join(', ')}),
  gutter: ${state.grid.gap}pt,
  ${components.join(',\n  ')}
)`;

            body.push(gridCode);
        }

        // Add spacing between rows
        body.push('#v(1em)');
    });

    // Combine all parts
    return `${header}\n\n${body.join('\n\n')}`;
}

function generateHeader(): string {
    return `// Typst Template
// Generated by PDF Template Builder

#set page(
  paper: "us-letter",
  margin: (x: 1in, y: 1in)
)

#set text(
  font: "Poppins",
  size: 11pt
)`;
}
